//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace convert_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public string message_id { get; set; }
        public string msg_status_id { get; set; }
        public string sender_id { get; set; }
        public string receiver_id { get; set; }
        public string content { get; set; }
        public System.DateTime sentAt { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual MessageStatu MessageStatu { get; set; }
    }
}
